"""transactions and sync checkpoints

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-03 02:48:57.076507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('last_block', sa.BigInteger(), nullable=True),
    sa.Column('cursor', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'syncing', 'synced', 'error')", name=op.f('ck_sync_checkpoints_status_valid')),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('fk_sync_checkpoints_wallet_id_wallets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_checkpoints')),
    sa.UniqueConstraint('wallet_id', name=op.f('uq_sync_checkpoints_wallet_id'))
    )
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('tx_hash', sa.String(length=128), nullable=False),
    sa.Column('transfer_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('from_address', sa.String(length=128), nullable=True),
    sa.Column('to_address', sa.String(length=128), nullable=True),
    sa.Column('value', sa.Numeric(precision=78, scale=0), nullable=True),
    sa.Column('token_address', sa.String(length=128), nullable=True),
    sa.Column('token_symbol', sa.String(length=32), nullable=True),
    sa.Column('token_decimals', sa.Integer(), nullable=True),
    sa.Column('fee', sa.Numeric(precision=78, scale=0), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('success', 'failed', 'pending')", name=op.f('ck_transactions_status_valid')),
    sa.CheckConstraint('transfer_index >= 0', name=op.f('ck_transactions_transfer_index_nonneg')),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('fk_transactions_wallet_id_wallets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('wallet_id', 'chain', 'tx_hash', 'transfer_index', name='uq_transactions_wallet_chain_hash_index')
    )
    op.create_index('ix_transactions_chain_tx_hash', 'transactions', ['chain', 'tx_hash'], unique=False)
    op.create_index('ix_transactions_wallet_id_block_number', 'transactions', ['wallet_id', 'block_number'], unique=False)
    op.create_index('ix_transactions_wallet_id_timestamp', 'transactions', ['wallet_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_wallet_id_timestamp', table_name='transactions')
    op.drop_index('ix_transactions_wallet_id_block_number', table_name='transactions')
    op.drop_index('ix_transactions_chain_tx_hash', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('sync_checkpoints')
    # ### end Alembic commands ###
