"""transaction classifications

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-03 02:59:41.553349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_classifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('tx_hash', sa.String(length=128), nullable=False),
    sa.Column('transfer_indexes', postgresql.ARRAY(sa.Integer()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('basis', sa.String(length=16), nullable=False),
    sa.Column('evidence_strength', sa.String(length=16), nullable=False),
    sa.Column('detection_method', sa.String(length=64), nullable=False),
    sa.Column('rule_version', sa.String(length=32), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('assets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uncertainty_notes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('tx_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('classified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(label = 'unknown') = (evidence_strength = 'none')", name=op.f('ck_transaction_classifications_unknown_iff_no_evidence')),
    sa.CheckConstraint("basis IN ('observed', 'inferred')", name=op.f('ck_transaction_classifications_basis_valid')),
    sa.CheckConstraint("evidence_strength IN ('strong', 'moderate', 'weak', 'none')", name=op.f('ck_transaction_classifications_strength_valid')),
    sa.CheckConstraint("label IN ('native_transfer', 'token_transfer', 'swap', 'bridge_transfer', 'exchange_deposit', 'exchange_withdrawal', 'contract_interaction', 'liquidity_add', 'liquidity_remove', 'mint', 'burn', 'nft_transfer', 'unknown')", name=op.f('ck_transaction_classifications_label_valid')),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('fk_transaction_classifications_wallet_id_wallets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_classifications')),
    sa.UniqueConstraint('wallet_id', 'chain', 'tx_hash', 'rule_version', name='uq_tx_class_wallet_chain_hash_version')
    )
    op.create_index('ix_tx_class_chain_tx_hash', 'transaction_classifications', ['chain', 'tx_hash'], unique=False)
    op.create_index('ix_tx_class_label', 'transaction_classifications', ['label'], unique=False)
    op.create_index('ix_tx_class_wallet_id_tx_timestamp', 'transaction_classifications', ['wallet_id', 'tx_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tx_class_wallet_id_tx_timestamp', table_name='transaction_classifications')
    op.drop_index('ix_tx_class_label', table_name='transaction_classifications')
    op.drop_index('ix_tx_class_chain_tx_hash', table_name='transaction_classifications')
    op.drop_table('transaction_classifications')
    # ### end Alembic commands ###
